### ISSUE TITLE
4.2 - Flipvec - isvector pass

### ISSUE THREAD

**Issue by bencorn** [bencorn/Cody-Coursework#2]
Student solution:

```
function out = flipvec(in)
    
    if isvector(in)
        out = flip(in);
    else
        out = in;
    end
    
end
```

isvector(in) returns true for both column or row vectors. The test for this should fail.

**Comment by aszetu** [comment]
Would this fix it? Also, not sure what the error message should say.

run('solution')
code = fileread('solution.m');
t=mtree(code);
matches = mtfind(t,'Kind','ID','String','isvector');
assert(isnull(matches),'Solution does not differentiate between column or row vectors.')

**Comment by bencorn** [comment]
This was for practice - there was actually nothing wrong with the solution ;)

The problem is supposed to flip (reverse the order) of the input if it is a vector and do nothing if it isn't a vector. flip() will reverse the same way regardless of it being a col or row vector.

If this had been a real bug, your solution is correct for checking the usage of isvector.
