### ISSUE TITLE
4.3 - Nexthour - Hardcoded Switch

### ISSUE THREAD

**Issue by bencorn** [bencorn/Cody-Coursework#3]
Student hardcoded (correct) passing solution.

```
function nexttime = nexthour(nowtime)
switch nowtime
    case 12
        nexttime = 1
    case 1
        nexttime = 2
    case 2
        nexttime = 3
    case 3
        nexttime = 4
    case 4
        nexttime = 5
    case 5
        nexttime = 6
    case 6 
        nexttime = 7
    case 7
        nexttime = 8
    case 8
        nexttime = 9
    case 9
        nexttime = 10
    case 10
        nexttime = 11
    case 11
        nexttime = 12
end
end
```

We should indicate that this is inefficient - either by not allowing switch or checking for a ton of cases. TBD in meetings.

**Comment by aszetu** [comment]
Again, not sure if these work.

Check for excessive cases:
run('solution')
code = fileread('solution.m');
t=mtree(code);
matches = mtfind(t,'Kind','ID','String','case');
cases = count(matches);
assert(cases > 3,’Solution is inefficient.’)

Check for switch:
run('solution')
code = fileread('solution.m');
t=mtree(code);
matches = mtfind(t,'Kind','ID','String','switch');
assert(isnull(matches),’Solution is inefficent')

**Comment by bencorn** [comment]
We are trying to move away from mtfind (m tree) usage as it is not officially supported by MATLAB and is undocumented. Try using strfind to accomplish the same thing - keeping in mind strfind returns a vector of instances.

I think we should just eliminate the usage the switch all together, so finding any instances of switch should cause the assert to fail... no need to check for case count at that point. Also try to make a small hint to the student if they do use switch.

**Comment by bencorn** [comment]
Solution merged into production. Test fails if switch is used.

%%
nowtime = 1;
nexttime_correct = 2;
assert(isequal(nexthour(nowtime),nexttime_correct))

nowtime = 12;
nexttime_correct = 1;
assert(isequal(nexthour(nowtime),nexttime_correct))

code = fileread('nexthour.m');
switchInstances = strfind(code,'switch');
assert(isempty(switchInstances), 'This problem is best solved using a range in an if condition. Try solving without switch.')
