### ISSUE TITLE
5.3 Inverse of e

### ISSUE THREAD

**Issue by gmichnovicz** [bencorn/Cody-Coursework#4]
7th Submission: All tests passed
Test Results
Submitted on 27 Feb 2017 at 0:19 by Omar Al Taee | Solution ID: 3719995	
 % write code to compute the value of the inverse to within the tolerance:
  
% store the value of n needed to reach this accuracy:
n=1840
while n<1
    n=n+1;
end
accurate_n = n

Someone just hardcoded the final value and wrote a while loop that will just never run...something to maybe fix?

**Comment by gmichnovicz** [comment]
I suppose we could maybe just test that at some point they define a value of e to make sure they don't hardcode a value of n...

code = fileread('solution.m');

defined_e=strfind(code,’exp(‘);
assert(~isempty(defined_e), ’The actual value of the inverse should be defined within your solution. ‘)
hardcode=strfind(code,'1840');
assert(isempty(hardcode),'Your solution should be calculated using loops.')

**Comment by bencorn** [comment]
Checking for exp() is good and should definitely be added. Make sure to include an explanation/hint as to why the check failed. We are moving away from m tree usage (mtfind) so the second approach you used is best.

We could also check to see if the value 1840 appears in their code. Since we use the same problems from semester to semester it could be a good idea.

**Comment by bencorn** [comment]
Solution merged into production.

%%
run('solution')

% check for variable existence. Do this for all named variables in the
% problem description or variables provided in the initial_display
vars = whos;

accurate_nExists = any(strcmpi('accurate_n',{vars.name}));
assert(accurate_nExists,'Make sure you define a variable with the name "accurate_n".')

% check that the student used a while loop
code = fileread('solution.m');
t = mtree(code);
matches = mtfind(t,'Kind','WHILE');
assert(~isnull(matches),'Your solution should use a WHILE loop.')

% the correct answer
correct_n = 1839; % if using &gt;
correct_n2 = 1840; % if using &gt;
  
assert(n == correct_n || n == correct_n2,'Your value of n is incorrect. Make sure your condition is correct and make sure you are changing your condition on every iteration of the loop.')

defined_e=strfind(code,'exp(');
assert(~isempty(defined_e), 'The actual value of the inverse should be defined within your solution. ')
hardcode=strfind(code,'1840');
assert(isempty(hardcode),'Your solution should be calculated using loops.')
