### ISSUE TITLE
8.4 Stock Api Issue

### ISSUE THREAD

**Issue by gmichnovicz** [bencorn/Cody-Coursework#6]
A couple different people did this and it's passing:

4th Submission: All tests passed
Test Results
Submitted about 19 hours ago by Renae Michael | Solution ID: 3922329	
 function data = stock_check(symbol)
% Help: stock_check('AAPL') returns relevant stock data about Apple.
% Markit Quote Endpoint
endpoint = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/json';
% Webread makes an HTTP GET request to Markit's Quote endpoint.
% webread(endpoint, key, value)
% The request parameter for this API call is just the symbol, these
% are in the form of 'key-value' pairs. Here the key is 'symbol' and the value
% is a stock symbol (i.e. AAPL).
resp = webread(endpoint, 'symbol', symbol);
% Run this code in MATLAB to determine the output of the API. It should
% return a data structure you are familiar with. Using the data structure,
% figure out how to extract the status, name, sign, stock price, percent change, and time stamp.
% Begin your code here:
data = {'Stock Name','%',50.00,4.0,'1:30'}
end

function data = stock_check(symbol)
% Help: stock_check('AAPL') returns relevant stock data about Apple.
% Markit Quote Endpoint
endpoint = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/json';
% Webread makes an HTTP GET request to Markit's Quote endpoint.
% webread(endpoint, key, value)
% The request parameter for this API call is just the symbol, these
% are in the form of 'key-value' pairs. Here the key is 'symbol' and the value
% is a stock symbol (i.e. AAPL).
resp = webread(endpoint, 'symbol', symbol);
% Run this code in MATLAB to determine the output of the API. It should
% return a data structure you are familiar with. Using the data structure,
% figure out how to extract the status, name, sign, stock price, percent change, and time stamp.
% Begin your code here:
data = {'Stock Name', '%', 5.25, 10, '10:24'}
end

Since the tests check each element of the return and none will fail since the elements are the right class, we need more checks to make sure they actually index the data structure.

**Comment by gmichnovicz** [comment]
code = fileread('solution.m');
check1=strfind(code, 'resp.Name');
assert(~isempty(check1), ’The name cell should hold data extracted from the response structure. ‘)
check2=strfind(code, 'resp.Symbol');
assert(~isempty(check2), ’The sign cell should hold data extracted from the response structure. ‘)
check3=strfind(code, 'resp.LastPrice');
assert(~isempty(check3), ’The status cell should hold data extracted from the response structure‘)
check4=strfind(code, 'resp.ChangePercent');
assert(~isempty(check4), ’The percent change cell should hold data extracted from the response structure‘)
check5=strfind(code, 'resp.Timestamp');
assert(~isempty(check5), ’The time stamp cell should hold data extracted from the response structure.‘)

Here's the index approach for now, I think it should work.

**Comment by bencorn** [comment]
We could check if they index each field in the response struct or we could also call the API locally within the script to generate the data and assert if their data matches our data generated by the API. Either way is fine but I do think we should check each field.

resp.Name and all of the others required.

**Comment by bencorn** [comment]
Cody problem has been updated. Please review changes below 🌮 

% Last Modified: 03/21/2017
% Last Modified by: Grace M., Ben C.

% Define Test Case
goog_sign = 'GOOGL';

% Run Student Function with Test Case
goog = stock_check(goog_sign);

% Is Output a Cell Array
assert(iscell(goog), 'Output of function should be a cell array.')

% Is Cell Array Correct Length
assert(length(goog) == 5, 'Output of function should return a cell array with five elements.')

% Check if Response Structure is Utilized
code = fileread('stock_check.m');
checkName=strfind(code, 'resp.Name');
assert(~isempty(checkName), 'The name cell should hold data extracted from the response structure.')
checkSymbol=strfind(code, 'resp.Symbol');
assert(~isempty(checkSymbol), 'The symbol cell should hold data extracted from the response structure.')
checkLastPrice=strfind(code, 'resp.LastPrice');
assert(~isempty(checkLastPrice), 'The status cell should hold data extracted from the response structure.')
checkChangePercent=strfind(code, 'resp.ChangePercent');
assert(~isempty(checkChangePercent), 'The percent change cell should hold data extracted from the response structure.')
checkTimeStamp=strfind(code, 'resp.Timestamp');
assert(~isempty(checkTimeStamp), 'The time stamp cell should hold data extracted from the response structure.')

% Check if Data is Correct
endpoint = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/json';
resp = webread(endpoint, 'symbol', 'GOOGL');
data = {resp.Name, resp.Symbol, resp.LastPrice, resp.ChangePercent, resp.Timestamp};

assert(isequal(data{1}, goog{1}), 'The first cell should contain the stock name.')
assert(isequal(data{2}, goog{2}), 'The second cell should contain the stock symbol.')
assert(isequal(data{3}, goog{3}), 'The third cell should contain the last price.')
assert(isequal(data{4}, goog{4}), 'The fourth cell should contain the percent change of the stock.')
assert(isequal(data{5}, goog{5}), 'The fifth cell should contain the time stamp of the data being retrieved.')
